"""new column and idx

Revision ID: 44bc2c52bbe3
Revises: b5a59b7b0104
Create Date: 2017-03-29 22:22:49.435795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44bc2c52bbe3'
down_revision = 'b5a59b7b0104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ARTIST', sa.Column('related_artist_id', sa.INTEGER(), nullable=True))
    op.create_index('id_idx', 'ARTIST', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id_idx', table_name='ARTIST')
    op.drop_column('ARTIST', 'related_artist_id')
    # ### end Alembic commands ###
