"""dropped table

Revision ID: b5a59b7b0104
Revises: 1586f309b075
Create Date: 2017-03-29 22:17:56.977371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a59b7b0104'
down_revision = '1586f309b075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('COMPANY')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('COMPANY',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('NAME', sa.TEXT(), nullable=False),
    sa.Column('AGE', sa.INTEGER(), nullable=False),
    sa.Column('ADDRESS', sa.CHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###
