"""nada

Revision ID: b8b1cc7766b3
Revises: 44bc2c52bbe3
Create Date: 2017-03-29 22:24:28.473469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b1cc7766b3'
down_revision = '44bc2c52bbe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
